@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

ECHO 必要な項目を設定してください
	SET /P PREFIX= フォルダ名の先頭につける文字列: 
	SET /P NUM= フォルダ数: 
	SET /P PAD= 番号の桁数: 

	SET COUNT=1
:LOOP
	IF %COUNT% GTR %NUM% (
		GOTO EXITLOOP
	)
	SET FOLDER=0000000000%COUNT%
	SET FOLDER=%PREFIX%!FOLDER:~-%PAD%!
	MKDIR %FOLDER%

	SET /A COUNT+=1
	GOTO LOOP

:EXITLOOP